const drinks = {
  idDrink: '17256',
  strDrink: 'Martinez 2',
  strDrinkAlternate: null,
  strDrinkES: null,
  strDrinkDE: null,
  strDrinkFR: null,
  'strDrinkZH-HANS': null,
  'strDrinkZH-HANT': null,
  strTags: null,
  strVideo: null,
  strCategory: 'Cocktail',
  strIBA: null,
  strAlcoholic: 'Alcoholic',
  strGlass: 'Cocktail glass',
  strInstructions: 'Add all ingredients to a mixing glass and fill with ice.\r\n\r\nStir until chilled, and strain into a chilled coupe glass.',
  strInstructionsES: null,
  strInstructionsDE: 'Alle Zutaten in ein Mischglas geben und mit Eis f\u00fcllen. Bis zum Abk\u00fchlen umr\u00fchren und in ein gek\u00fchltes Coup\u00e9glas abseihen.',
  strInstructionsFR: null,
  'strInstructionsZH-HANS': null,
  'strInstructionsZH-HANT': null,
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/fs6kiq1513708455.jpg',
  strIngredient1: 'Gin',
  strIngredient2: 'Sweet Vermouth',
  strIngredient3: 'Maraschino Liqueur',
  strIngredient4: 'Angostura Bitters',
  strMeasure1: '1 1/2 oz',
  strMeasure2: '1 1/2 oz',
  strMeasure3: '1 tsp',
  strMeasure4: '2 dashes',
  strCreativeCommonsConfirmed: 'No',
};

export default drinks;
