const checkedlist = {
  checkbox: [
    { id: 0, name: '', checked: false },
    { id: 1, checked: false },
    { id: 2, checked: false },
    { id: 3, checked: false },
    { id: 4, checked: false },
    { id: 5, checked: false },
    { id: 6, checked: false },
    { id: 7, checked: false },
    { id: 8, checked: false },
    { id: 9, checked: false },
    { id: 10, checked: false },
    { id: 11, checked: false },
    { id: 12, checked: false },
    { id: 13, checked: false },
    { id: 14, checked: false },
    { id: 15, checked: false },
    { id: 16, checked: false },
    { id: 17, checked: false },
    { id: 18, checked: false },
    { id: 19, checked: false },
    { id: 20, checked: false },
  ],
};

export const checkedList = {
  checkbox: [
    { id: 0, name: '', checked: false },
    { id: 1, checked: false },
    { id: 2, checked: false },
    { id: 3, checked: false },
    { id: 4, checked: false },
    { id: 5, checked: false },
    { id: 6, checked: false },
    { id: 7, checked: false },
    { id: 8, checked: false },
    { id: 9, checked: false },
    { id: 10, checked: false },
    { id: 11, checked: false },
    { id: 12, checked: false },
    { id: 13, checked: false },
    { id: 14, checked: false },
    { id: 15, checked: false },
    { id: 16, checked: false },
    { id: 17, checked: false },
    { id: 18, checked: false },
    { id: 19, checked: false },
    { id: 20, checked: false },
  ],
};

export default checkedlist;
